#!/usr/bin/env python
"""
main data collector program
"""
from scrapers import openclassrooms, udemy, pluralsight, globalknowledge
import utils

# udemy.run()
# pluralsight.run()
# globalknowledge.run()
globalknowledge = globalknowledge.GlobalKnowledge('globalknowledge', utils.constants.CATEGORIES['education'])
globalknowledge.run()
# openclassrooms.run()  # FOR TESTING (fastest)

# utils.cli.server()
