#!/usr/bin/env python
"""
main data collector program
TODO rearrange modules __init__ imports (=> from scrapers import udemy, openclassrooms, ...)
TODO implement DB
"""
from scrapers.openclassrooms import openclassrooms
from scrapers.globalknowledge import globalknowledge
from scrapers.pluralsight import pluralsight
from scrapers.udemy import udemy
import utils

# udemy.run()
# pluralsight.run()
# globalknowledge.run()
# openclassrooms.run()

utils.cli.server()
