#!/usr/bin/env python
"""
main data collector program
TODO convert scrapers modules (.py) in class modules
TODO implement DB
"""
from scrapers import openclassrooms, udemy, pluralsight, globalknowledge
import utils

# udemy.run()
# pluralsight.run()
# globalknowledge.run()
openclassrooms.run()  # FOR TESTING (fastest)

# utils.cli.server()
